export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//foreigner registration
export const USER_REGISTRATION_START = "USER_REGISTRATION_START";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE"

//Data fetch
export const LIST_FETCH_START = "LIST_FETCH_START";
export const LIST_FETCH_SUCCESS = "LIST_FETCH_SUCCESS";
export const LIST_FETCH_FAILURE = "LIST_FETCH_FAILURE";

//Single Data fetch
export const SINGLE_DATA_FACE_START = "SINGLE_DATA_FACE_START";
export const SINGLE_DATA_FACE_SUCCESS = "SINGLE_DATA_FACE_SUCCESS";
export const SINGLE_DATA_FACE_FAILURE = "LIST_FETCH_FAILURE";

//Data add
export const DATA_ADD_START = "DATA_ADD_START";
export const DATA_ADD_SUCCESS = "DATA_ADD_SUCCESS";
export const DATA_ADD_FAILURE = "DATA_ADD_FAILURE";

//Data edit
export const DATA_EDIT_START = "DATA_EDIT_START";
export const DATA_EDIT_SUCCESS = "DATA_EDIT_SUCCESS";
export const DATA_EDIT_FAILURE = "DATA_EDIT_FAILURE";

//Data delete
export const DATA_DELETE_START = "DATA_DELETE_START";
export const DATA_DELETE_SUCCESS = "DATA_DELETE_SUCCESS";
export const DATA_DELETE_FAILURE = "DATA_DELETE_FAILURE";